# Generated by Django 5.2.16 on 2026-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(choices=[('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish')], default='neutral', max_length=10)),
                ('vader_score', models.FloatField(default=0.0)),
                ('textblob_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_prices', models.JSONField(default=list)),
                ('actual_prices', models.JSONField(default=list)),
                ('prediction_dates', models.JSONField(default=list)),
                ('days_predicted', models.IntegerField(default=30)),
                ('include_sentiment', models.BooleanField(default=False)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('directional_accuracy', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM'), ('gru', 'GRU'), ('bilstm', 'Bidirectional LSTM')], default='lstm', max_length=10)),
                ('model_path', models.CharField(max_length=500)),
                ('scaler_path', models.CharField(max_length=500)),
                ('sequence_length', models.IntegerField(default=60)),
                ('epochs_trained', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=32)),
                ('features_used', models.JSONField(default=list)),
                ('loss_history', models.JSONField(default=list)),
                ('val_loss_history', models.JSONField(default=list)),
                ('final_train_loss', models.FloatField(blank=True, null=True)),
                ('final_val_loss', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trained Model',
                'verbose_name_plural': 'Trained Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='api_stockda_ticker_0b0e29_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
